# This rule is not used by the project access-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pods.k8s.delta10.nl.k8s.delta10.nl.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: access-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresaccess-admin-role
rules:
- apiGroups:
  - pods.k8s.delta10.nl.k8s.delta10.nl
  resources:
  - postgresaccesses
  verbs:
  - '*'
- apiGroups:
  - pods.k8s.delta10.nl.k8s.delta10.nl
  resources:
  - postgresaccesses/status
  verbs:
  - get
