# This rule is not used by the project access-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to access.k8s.delta10.nl resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: access-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresaccess-viewer-role
rules:
- apiGroups:
  - access.k8s.delta10.nl
  resources:
  - postgresaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.k8s.delta10.nl
  resources:
  - postgresaccesses/status
  verbs:
  - get
